version: '3.8'

services:
  app:
    build:
      context: . # Build from the current directory
    ports:
      - "3000:3000" # Map port 3000 of the container to port 3000 of the host
    command: npm run start # Override the CMD in the Dockerfile
